package ontology;

public enum MessageInfo {
	AGENTS_KNOWN_TO_COALITION, CANCELLING_NEGOTIATION, CONFIRM_YOUR_PARTICIPATION, CONFIRMING_MY_PARTICIPATION, DEMAND, INVITATION, INVITATION_REJECTED, KNOWN_AGENTS, LEAVING_COALITION, NEGOTIATION_CANCELLED, NEGOTIATION_UNSUCCESSFUL, NEW_COALITION, REJECTING_INVITATION
}
